# Full PCA Analysis Configuration
# Runs all variations with multiple PCA component settings

target: ptsd_bin

n_folds: 5
n_iterations: 5

sample_fraction: 1.0

# Test multiple PCA dimensions
pca_components: [10, 20, 50, 100, 200]

# Run all variations
variations:
  regular: true
  regular_filtered: true
  kfold: true
  kfold_filtered: true

pcl_filtering:
  remove_intermediate: true
  ptsd_threshold: 33
  buffer: 8

output:
  base_dir: ml_output
  generate_report: true
  
scp:
  enabled: true
  destination: /Users/michaelzakariaie/Desktop

advanced:
  random_state: 42
  test_size: 0.2
  delay_between_runs: 2