# K-Fold Only Analysis Configuration
# Runs exactly 3 variations (k-fold only):
# 1. Binary classification (ptsd_bin) - k-fold
# 2. Binary classification (ptsd_bin) - k-fold with PCL filtering
# 3. Regression (pcl_score) - k-fold

# This configuration uses the multi_target feature to run different targets with different settings
multi_target:
  # Binary classification variations (2 k-fold only)
  - target: ptsd_bin
    variations:
      regular: false          # Skip regular runs
      regular_filtered: false # Skip regular filtered runs
      kfold: true            # Variation 1: Binary - k-fold
      kfold_filtered: true   # Variation 2: Binary - k-fold filtered

  # Regression variations (1 k-fold only - no filtering)
  - target: pcl_score
    variations:
      regular: false         # Skip regular runs
      regular_filtered: false
      kfold: true           # Variation 3: Regression - k-fold  
      kfold_filtered: false

# K-fold settings
n_folds: 5          # 5-fold cross-validation
n_iterations: 1     # Repeat k-fold 5 times for robust results

# Data settings
sample_fraction: 0.05  # Use full dataset
pca_components: []    # No PCA analysis

# PCL filtering settings (only applied to binary classification)
pcl_filtering:
  remove_intermediate: true
  ptsd_threshold: 33
  buffer: 8

# Output settings
output:
  base_dir: ml_output
  generate_report: true

# SCP transfer settings
scp:
  enabled: true  # Show SCP command after completion
  destination: /Users/michaelzakariaie/Desktop/Insight_Runs

# Feature engineering settings
feature_engineering:
  use_rfecv: false          # Use Recursive Feature Elimination with CV
  rfecv_step: 1            # Number of features to remove at each iteration
  rfecv_min_features: 5    # Minimum features to keep
  
# Model selection settings
models:
  # Which models to include in the pipeline
  include_models:
    - 'Logistic Regression'
    - 'Naive Bayes'
    - 'Random Forest'
    - 'Gradient Boosting'
    - 'XGBoost'
    - 'SVM'
    - 'SVM_Poly'
    - 'Neural Network'
    - 'Deep NN'
    - 'Wide NN'
    - 'Funnel NN'
  
  # Models to exclude (overrides include_models)
  exclude_models: []

# Hyperparameter tuning settings
hyperparameter_tuning:
  enabled: false            # Enable automatic hyperparameter tuning
  use_random_search: true   # Use RandomizedSearchCV vs GridSearchCV
  n_iter: 30               # Number of iterations for random search
  top_models: 3            # Number of top models to tune
  models_to_tune:          # Specific models to tune (if empty, uses top_models)
    - 'XGBoost'
    - 'Random Forest'
    - 'Gradient Boosting'

# Automated pipeline settings
automated_pipeline:
  enabled: false           # Run fully automated pipeline with RFECV + tuning
  
# Advanced settings
advanced:
  random_state: 42
  test_size: 0.2
  delay_between_runs: 2
  n_jobs: -1              # Number of parallel jobs (-1 for all cores)
  verbose: 1              # Verbosity level